version: '3'

services:
  database:
    image: "postgres:12"
    env_file: .env
    restart: always
    volumes:
      - "odoo-pg-data:/var/lib/postgresql/data"
  app:
    build: .
    env_file: .env
    restart: always
    ports:
      - "8069:8069"
    links:
      - "database:database"
    volumes:
      - "odoo-shared-data:/home/app/.local/share/Odoo"

volumes:
  odoo-shared-data:
  odoo-pg-data:
